### PR TITLE
Rawbinwrapper fixes

### PR DESCRIPTION
**Pull request by ctw**

### CODE REVIEW

**Comment by psederberg** [comment]
Why are there 16 commits for just 6 lines of changes?

**Comment by ctw** [comment]
Some commits from previous pull requests appear here as well -- not sure why ...

**Comment by psederberg** [comment]
Why don't I just make this change by hand in my branch and then you can
re-clone so this is all clean moving forward?

**Comment by ctw** [comment]
Sure!

**Comment by psederberg** [comment]
Made changes separately and merged...

**Pull request closed without merging**
